// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YEJMHRtZ875iEXEormOgpeoveplLmqQ',
    appId: '1:575327975025:android:8acc4d5ab6041086b0cdd0',
    messagingSenderId: '575327975025',
    projectId: 'a-idiot-ddalgguk',
    storageBucket: 'a-idiot-ddalgguk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRbiTPteUIg3F4_72OmC77EPMhgbh5fSk',
    appId: '1:575327975025:ios:eb1970783a805436b0cdd0',
    messagingSenderId: '575327975025',
    projectId: 'a-idiot-ddalgguk',
    storageBucket: 'a-idiot-ddalgguk.firebasestorage.app',
    androidClientId:
        '575327975025-0tqgdncpri7ikebkgcmcgmq915dl7ljg.apps.googleusercontent.com',
    iosClientId:
        '575327975025-9d0tkm3ounk9thbsdt651muljo7po2vl.apps.googleusercontent.com',
    iosBundleId: 'com.aidiot.ddalgguk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRbiTPteUIg3F4_72OmC77EPMhgbh5fSk',
    appId: '1:575327975025:ios:eb1970783a805436b0cdd0',
    messagingSenderId: '575327975025',
    projectId: 'a-idiot-ddalgguk',
    storageBucket: 'a-idiot-ddalgguk.firebasestorage.app',
    androidClientId:
        '575327975025-0tqgdncpri7ikebkgcmcgmq915dl7ljg.apps.googleusercontent.com',
    iosClientId:
        '575327975025-9d0tkm3ounk9thbsdt651muljo7po2vl.apps.googleusercontent.com',
    iosBundleId: 'com.aidiot.ddalgguk',
  );
}
